select
    r.variant_col:"_id"."$oid"::string as receipt_id,
    i.value:"barcode"::string as barcode,
    i.value:"description"::string as description,
    i.value:"finalPrice"::string as finalprice,
    i.value:"itemPrice"::string as itemprice,
    i.value:"needsFetchReview"::boolean as needsfetchreview,
    i.value:"partnerItemId"::string as partneritemid,
    i.value:"preventTargetGapPoints"::boolean as preventtargetgappoints,
    i.value:"quantityPurchased"::number as quantitypurchased,
    i.value:"userFlaggedBarcode"::string as userflaggedbarcode,
    i.value:"userFlaggedNewItem"::boolean as userflaggednewitem,
    i.value:"userFlaggedPrice"::string as userflaggedprice,
    i.value:"userFlaggedQuantity"::number as userflaggedquantity,
    i.value:"needsFetchReviewReason"::string as needsfetchreviewreason,
    i.value:"pointsNotAwardedReason"::string as pointsnotawardedreason,
    i.value:"pointsPayerId"::string as pointspayerid,
    i.value:"rewardsGroup"::string as rewardsgroup,
    i.value:"rewardsProductPartnerId"::string as rewardsproductpartnerid,
    i.value:"userFlaggedDescription"::string as userflaggeddescription,
    i.value:"originalMetaBriteBarcode"::string as originalmetabritebarcode,
    i.value:"originalMetaBriteDescription"::string as originalmetabritedescription,
    i.value:"brandCode"::string as brandcode,
    i.value:"competitorRewardsGroup"::string as competitorrewardsgroup,
    i.value:"discountedItemPrice"::string as discounteditemprice,
    i.value:"originalReceiptItemText"::string as originalreceiptitemtext,
    i.value:"itemNumber"::string as itemnumber,
    i.value:"originalMetaBriteQuantityPurchased"::number
    as originalmetabritequantitypurchased,
    i.value:"pointsEarned"::string as pointsearned,
    i.value:"targetPrice"::string as targetprice,
    i.value:"competitiveProduct"::string as competitiveproduct,
    i.value:"originalFinalPrice"::string as originalfinalprice,
    i.value:"originalMetaBriteItemPrice"::string as originalmetabriteitemprice,
    i.value:"deleted"::boolean as deleted,
    i.value:"priceAfterCoupon"::string as priceaftercoupon,
    i.value:"metabriteCampaignId"::string as metabritecampaignid
from
    raw_fetch_excercise.receipts.receipts_tbl r,
    lateral flatten(input => r.variant_col:"rewardsReceiptItemList") i
;
